steps:
  - name: gcr.io/cloud-builders/docker
    args: [yarn, '-t', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/master-build/build:latest', '.']
images:
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/master-build/build:latest'
options: 
  logging: CLOUD_LOGGING_ONLY
